### ISSUE TITLE
Just updated coc.nvim Plugin and now highlights don't work on autocompletion

### ISSUE THREAD

**Issue by nathandrew** [bignimbus/pop-punk.vim#7]
![image](https://user-images.githubusercontent.com/7018871/191085270-491e600e-f5fb-4e4d-b7af-a9d76ee80e39.png)

Highlight color is very faint.

Anyone else running into this issue?

**Comment by bignimbus** [comment]
Hi @nathandrew, sorry for the delayed response.  Can you try on branch `experimental`?  I've updated the `CocMenuSel` highlight group to be explicit rather than passively accepting the value that `coc.nvim` gives.

```vim
Plug 'bignimbus/pop-punk.vim', { 'branch': 'experimental' }
```

I'll probably merge this into `main` soon because I made some other enhancements to TypeScript, Markdown, CSS, and GraphQL that make me happy.
